allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@astrojs/internal-helpers@0.11.0'
  - '@astrojs/markdown-satteri@0.4.0'
  - '@astrojs/netlify@8.2.8'
  - '@astrojs/react@6.0.6'
  - '@astrojs/sitemap@3.7.4'
  - '@lucide/astro@1.53.0'
  - astro@7.3.7
  - lucide-react@1.53.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
publicHoistPattern:
  - '*astro*'
  - '*eslint*'
  - '*typescript*'
