// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/resume": {
    params: {};
  };
  "/:content/:slug": {
    params: {
      "content": string;
      "slug": string;
    };
  };
  "/dev/sentry-test": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/resume" | "/:content/:slug" | "/dev/sentry-test";
  };
  "./routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "./routes/resume.ts": {
    id: "routes/resume";
    page: "/resume";
  };
  "./routes/$content.$slug.tsx": {
    id: "routes/$content.$slug";
    page: "/:content/:slug";
  };
  "./routes/dev.sentry-test.tsx": {
    id: "routes/dev.sentry-test";
    page: "/dev/sentry-test";
  };
};