name: PR

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

concurrency:
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  pr-title:
    name: Title
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          disallowScopes: |
            .+
          requireScope: false
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
